import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/providers/ThemeProvider";
import TanStackProvider from "@/components/providers/TanStackProvider";
import { cookies } from "next/headers"; // To access cookies on the server

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "RediStash",
  description: "Generated by create next app",
};

// Helper function to get the initial theme from cookies
async function getInitialTheme() {
  const cookieStore = await cookies(); // Await the Promise to get ReadonlyRequestCookies
  const theme = cookieStore.get("theme")?.value;
  return theme || "system"; // Fallback to 'system' if no theme cookie is set
}

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const initialTheme = await getInitialTheme(); // Await the async function
  const themeClass = initialTheme === "dark" ? "dark" : ""; // Simplified theme logic

  return (
    <html lang="en" className={themeClass} suppressHydrationWarning>
      <body className={inter.className}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <TanStackProvider>{children}</TanStackProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
